[package]
name = "crowdfunds"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
SupraOracle = { local = "../svalue-feed-framework" }

[addresses]
crowdfunds = "0x0"
sui = "0x2"
